services:
  database:
    container_name: osmdatabase
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osm
      MYSQL_USER: osmuser
      MYSQL_PASSWORD: osmpass
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: osmphp
    build:
      context: ./php
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: osmphpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80